//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmdNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cmdNet.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت شبکه cmdNet.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string Btn_English {
            get {
                return ResourceManager.GetString("Btn_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string Btn_Persian {
            get {
                return ResourceManager.GetString("Btn_Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرا.
        /// </summary>
        public static string Btn_Run {
            get {
                return ResourceManager.GetString("Btn_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی فایروال ویندوز به تنظیمات کارخانه..
        /// </summary>
        public static string Cmd_AdvfirewallReset {
            get {
                return ResourceManager.GetString("Cmd_AdvfirewallReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش جدول ARP شامل آدرس‌های MAC و IP دستگاه‌های متصل..
        /// </summary>
        public static string Cmd_Arp {
            get {
                return ResourceManager.GetString("Cmd_Arp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آدرس MAC کارت‌های شبکه سیستم..
        /// </summary>
        public static string Cmd_Getmac {
            get {
                return ResourceManager.GetString("Cmd_Getmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش نام کامپیوتر فعلی..
        /// </summary>
        public static string Cmd_Hostname {
            get {
                return ResourceManager.GetString("Cmd_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش تنظیمات آی‌پی تمام کارت‌های شبکه..
        /// </summary>
        public static string Cmd_InterfaceIpShowConfig {
            get {
                return ResourceManager.GetString("Cmd_InterfaceIpShowConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریست کامل TCP/IP و استک (پشته) شبکه به حالت اولیه (نیاز به ریستارت)..
        /// </summary>
        public static string Cmd_IntIpReset {
            get {
                return ResourceManager.GetString("Cmd_IntIpReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی اختصاصی پروتکل IPv4 (نیاز به ریستارت)..
        /// </summary>
        public static string Cmd_IntIpv4Reset {
            get {
                return ResourceManager.GetString("Cmd_IntIpv4Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی اختصاصی پروتکل IPv6 (نیاز به ریستارت)..
        /// </summary>
        public static string Cmd_IntIpv6Reset {
            get {
                return ResourceManager.GetString("Cmd_IntIpv6Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش تنظیمات IP، آدرس MAC، Gateway و DNS سیستم..
        /// </summary>
        public static string Cmd_Ipconfig {
            get {
                return ResourceManager.GetString("Cmd_Ipconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش کامل تنظیمات شبکه شامل DHCP، DNS، آدرس‌های MAC و بیشتر..
        /// </summary>
        public static string Cmd_IpconfigAll {
            get {
                return ResourceManager.GetString("Cmd_IpconfigAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش محتویات کش DNS (آی‌پی‌های ذخیره‌شده)..
        /// </summary>
        public static string Cmd_IpconfigDisplaydns {
            get {
                return ResourceManager.GetString("Cmd_IpconfigDisplaydns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن کش DNS برای رفع خطاهای باز نشدن وب‌سایت‌ها..
        /// </summary>
        public static string Cmd_IpconfigFlushdns {
            get {
                return ResourceManager.GetString("Cmd_IpconfigFlushdns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزاد کردن آدرس IP فعلی از DHCP..
        /// </summary>
        public static string Cmd_IpconfigRelease {
            get {
                return ResourceManager.GetString("Cmd_IpconfigRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست مجدد آدرس IP از DHCP..
        /// </summary>
        public static string Cmd_IpconfigRenew {
            get {
                return ResourceManager.GetString("Cmd_IpconfigRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اتصالات شبکه فعلی، ممکن است کند باشد..
        /// </summary>
        public static string Cmd_Netstat {
            get {
                return ResourceManager.GetString("Cmd_Netstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش تمام اتصالات و پورت‌ها به‌صورت عددی بدون تبدیل DNS..
        /// </summary>
        public static string Cmd_NetstatAn {
            get {
                return ResourceManager.GetString("Cmd_NetstatAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش برنامه‌هایی که از پورت‌ها استفاده می‌کنند (نیاز به دسترسی ادمین)..
        /// </summary>
        public static string Cmd_NetstatB {
            get {
                return ResourceManager.GetString("Cmd_NetstatB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آمار Ethernet شامل تعداد بسته‌ها، خطاها و غیره..
        /// </summary>
        public static string Cmd_NetstatE {
            get {
                return ResourceManager.GetString("Cmd_NetstatE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر اتصالات فعال که در وضعیت ESTABLISHED هستند..
        /// </summary>
        public static string Cmd_NetstatEstablished {
            get {
                return ResourceManager.GetString("Cmd_NetstatEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پورت‌هایی که در حالت LISTEN هستند..
        /// </summary>
        public static string Cmd_NetstatListen {
            get {
                return ResourceManager.GetString("Cmd_NetstatListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آدرس‌ها بدون تبدیل به نام دامنه..
        /// </summary>
        public static string Cmd_NetstatN {
            get {
                return ResourceManager.GetString("Cmd_NetstatN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش شناسه پردازش (PID) برای هر اتصال..
        /// </summary>
        public static string Cmd_NetstatO {
            get {
                return ResourceManager.GetString("Cmd_NetstatO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اتصالات روی پورت 443 (HTTPS)..
        /// </summary>
        public static string Cmd_NetstatPort443 {
            get {
                return ResourceManager.GetString("Cmd_NetstatPort443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اتصالات روی پورت 80 (HTTP)..
        /// </summary>
        public static string Cmd_NetstatPort80 {
            get {
                return ResourceManager.GetString("Cmd_NetstatPort80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش جدول مسیریابی سیستم (Route Table)..
        /// </summary>
        public static string Cmd_NetstatR {
            get {
                return ResourceManager.GetString("Cmd_NetstatR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آمار پروتکل‌های شبکه مانند TCP، UDP، ICMP..
        /// </summary>
        public static string Cmd_NetstatS {
            get {
                return ResourceManager.GetString("Cmd_NetstatS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی آدرس IP دامنه bing.com از طریق DNS..
        /// </summary>
        public static string Cmd_Nslookup {
            get {
                return ResourceManager.GetString("Cmd_Nslookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تست اتصال به سرور گوگل و بررسی پاسخ‌دهی شبکه..
        /// </summary>
        public static string Cmd_Ping {
            get {
                return ResourceManager.GetString("Cmd_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش جدول مسیریابی سیستم و مسیرهای شبکه..
        /// </summary>
        public static string Cmd_Route {
            get {
                return ResourceManager.GetString("Cmd_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اطلاعات کامل سیستم شامل نسخه ویندوز، شبکه و سخت‌افزار..
        /// </summary>
        public static string Cmd_Systeminfo {
            get {
                return ResourceManager.GetString("Cmd_Systeminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مسیر بسته‌ها تا رسیدن به سرور 8.8.8.8 (DNS گوگل)..
        /// </summary>
        public static string Cmd_Tracert {
            get {
                return ResourceManager.GetString("Cmd_Tracert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریست Winsock برای رفع اختلالات اتصال اینترنت و خطاهای نرم‌افزاری (نیاز به ریستارت)..
        /// </summary>
        public static string Cmd_WinsockReset {
            get {
                return ResourceManager.GetString("Cmd_WinsockReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پروفایل‌های وای‌فای ذخیره‌شده در سیستم..
        /// </summary>
        public static string Cmd_WlanShowProfile {
            get {
                return ResourceManager.GetString("Cmd_WlanShowProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستور:.
        /// </summary>
        public static string Lbl_Command {
            get {
                return ResourceManager.GetString("Lbl_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی:.
        /// </summary>
        public static string Lbl_Output {
            get {
                return ResourceManager.GetString("Lbl_Output", resourceCulture);
            }
        }
    }
}
